-- ====================================================================================
-- DUMP DATABASE JURNAL MENGAJAR (NORMALIZED)
-- ====================================================================================

-- --------------------------------------------------------
-- 1. BUAT TABEL PROFIL & MASTER DATA
-- --------------------------------------------------------

-- Tabel Profiles
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY, -- References auth.users(id)
    email text,
    nama_lengkap text,
    role text CHECK (role IN ('admin', 'guru')),
    jabatan text,
    alamat text,
    no_telp text,
    foto_url text
);

-- Master Kelas
CREATE TABLE public.master_kelas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kelas text NOT NULL UNIQUE
);

-- Master Mata Pelajaran
CREATE TABLE public.master_mata_pelajaran (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_mata_pelajaran text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

-- Master Periode Ajaran
CREATE TABLE public.master_periode (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_periode text NOT NULL,
    is_active boolean DEFAULT false
);

-- Master Jam / Waktu Pelajaran
CREATE TABLE public.master_jam (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jam_ke integer NOT NULL UNIQUE,
    waktu_reguler text NOT NULL,
    waktu_puasa text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- Master Siswa
CREATE TABLE public.master_siswa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_siswa text NOT NULL,
    nisn text,
    kelas_id bigint NOT NULL REFERENCES public.master_kelas(id) ON DELETE CASCADE
);


-- --------------------------------------------------------
-- 2. BUAT TABEL TRANSAKSIONAL (JADWAL, JURNAL, PRESENSI)
-- --------------------------------------------------------

-- Jadwal Mengajar
CREATE TABLE public.jadwal_mengajar (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guru_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    periode_id bigint REFERENCES public.master_periode(id) ON DELETE CASCADE,
    kelas_id bigint REFERENCES public.master_kelas(id) ON DELETE CASCADE,
    mata_pelajaran_id bigint REFERENCES public.master_mata_pelajaran(id) ON DELETE CASCADE,
    jam_id bigint REFERENCES public.master_jam(id) ON DELETE CASCADE,
    hari integer CHECK (hari >= 1 AND hari <= 7), -- Calculated via trigger
    tanggal date,
    is_active boolean DEFAULT true
);

-- Jurnal Harian
CREATE TABLE public.jurnal_harian (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jadwal_id bigint NOT NULL REFERENCES public.jadwal_mengajar(id) ON DELETE CASCADE,
    tanggal date DEFAULT CURRENT_DATE,
    materi text NOT NULL,
    catatan text,
    foto_lampiran_url text,
    is_telat boolean DEFAULT false,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    catatan_admin text,
    validated_by uuid REFERENCES public.profiles(id),
    validated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- Presensi Siswa
CREATE TABLE public.presensi_siswa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jurnal_id bigint NOT NULL REFERENCES public.jurnal_harian(id) ON DELETE CASCADE,
    siswa_id bigint NOT NULL REFERENCES public.master_siswa(id) ON DELETE CASCADE,
    kelas_id bigint REFERENCES public.master_kelas(id),
    status text DEFAULT 'Hadir' CHECK (status IN ('Hadir', 'Sakit', 'Izin', 'Alpha', 'H', 'S', 'I', 'A'))
);


-- --------------------------------------------------------
-- 3. SEEDING DATA AWAL (SEEDER)
-- --------------------------------------------------------

INSERT INTO public.master_kelas (nama_kelas) VALUES
('X RPL 1'), ('X RPL 2'), ('XI RPL 1'), ('XI RPL 2'), ('XII RPL 1');

INSERT INTO public.master_mata_pelajaran (nama_mata_pelajaran) VALUES
('Pemrograman Web'), 
('Basis Data'), 
('Pemrograman Berbasis Objek'), 
('Matematika'), 
('Bahasa Indonesia'), 
('Bahasa Inggris'),
('Pendidikan Agama dan Budi Pekerti'), 
('Pendidikan Pancasila dan Kewarganegaraan (PPKn)'), 
('Sejarah Indonesia'), 
('Seni Budaya'), 
('Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)'), 
('Dasar Desain Grafis'), 
('Pemrograman Dasar'), 
('Komputer dan Jaringan Dasar'), 
('Sistem Komputer'), 
('Produk Kreatif dan Kewirausahaan (PKK)');

INSERT INTO public.master_periode (nama_periode, is_active) VALUES
('2025/2026 Ganjil', false),
('2025/2026 Genap', true);

INSERT INTO public.master_jam (jam_ke, waktu_reguler, waktu_puasa) VALUES
(1, '07.00-07.50', '07.30-08.05'),
(2, '07.50-08.40', '08.05-08.40'),
(3, '08.45-09.35', '08.45-09.20'),
(4, '09.35-10.25', '09.20-09.55'),
(5, '10.30-11.20', '10.00-10.35'),
(6, '11.20-12.10', '10.35-11.10'),
(7, '13.10-14.00', '11.10-11.45'),
(8, '14.00-14.50', '13.00-13.35'),
(9, '14.55-15.45', '13.35-14.10'),
(10, '15.45-16.35', '14.10-14.45'),
(11, '18.15-19.05', '15.15-15.45'),
(12, '19.05-19.55', '15.45-16.15');

INSERT INTO public.master_siswa (nama_siswa, nisn, kelas_id) VALUES
-- Kelas 1 (X RPL 1)
('Ahmad Fauzi', '100010001', 1),
('Budi Santoso', '100010002', 1),
('Citra Kirana', '100010003', 1),
('Dian Sastro', '100010004', 1),
('Eko Prasetyo', '100010005', 1),
('Fani Rahmawati', '100010006', 1),
('Gilang Dirga', '100010007', 1),
('Hani Handayani', '100010008', 1),
('Irfan Hakim', '100010009', 1),
('Joko Suprianto', '100010010', 1),
-- Kelas 2 (X RPL 2)
('Kurnia Meiga', '200020001', 2),
('Lesti Kejora', '200020002', 2),
('Muhammad Iqbal', '200020003', 2),
('Nina Zatulini', '200020004', 2),
('Oki Setiana', '200020005', 2),
('Pratama Arhan', '200020006', 2),
('Qoriatul Hayati', '200020007', 2),
('Rizky Billar', '200020008', 2),
('Siti Badriah', '200020009', 2),
('Taufik Hidayat', '200020010', 2),
-- Kelas 3 (XI RPL 1)
('Umi Kulsum', '300030001', 3),
('Vina Panduwinata', '300030002', 3),
('Wawan Hendrawan', '300030003', 3),
('Xena Xandria', '300030004', 3),
('Yanti Yulianti', '300030005', 3),
('Zainuddin', '300030006', 3),
('Agung Saputra', '300030007', 3),
('Bayu Santoso', '300030008', 3),
('Coki Pratama', '300030009', 3),
('Deddy Gunawan', '300030010', 3);

-- Dummy Profiles Guru
INSERT INTO public.profiles (id, nama_lengkap, role, jabatan, email) VALUES 
('11111111-1111-1111-1111-111111111111', 'Bagus Hidayat', 'guru', 'Guru Pemrograman', 'bagus@sekolah.com'),
('22222222-2222-2222-2222-222222222222', 'Ahmad Fauzan', 'guru', 'Guru Basis Data', 'fauzan@sekolah.com'),
('33333333-3333-3333-3333-333333333333', 'Yunida Maudy', 'guru', 'Guru Umum', 'yunida@sekolah.com');

-- Seeder Jadwal Mengajar
-- guru_id, periode_id(2), kelas_id(1-5), mapel_id(1-16), jam_id(1-12), hari(1-5)
INSERT INTO public.jadwal_mengajar (guru_id, periode_id, kelas_id, mata_pelajaran_id, jam_id, hari) VALUES
-- Hari Senin (1)
('11111111-1111-1111-1111-111111111111', 2, 1, 1, 1, 1), -- Bagus, X RPL 1, Pemrograman Web, Jam 1
('11111111-1111-1111-1111-111111111111', 2, 1, 1, 2, 1), -- Bagus, X RPL 1, Pemrograman Web, Jam 2
('22222222-2222-2222-2222-222222222222', 2, 2, 2, 3, 1), -- Fauzan, X RPL 2, Basis Data, Jam 3
('22222222-2222-2222-2222-222222222222', 2, 2, 2, 4, 1), -- Fauzan, X RPL 2, Basis Data, Jam 4
('33333333-3333-3333-3333-333333333333', 2, 3, 4, 5, 1), -- Yunida, XI RPL 1, Matematika, Jam 5
('33333333-3333-3333-3333-333333333333', 2, 3, 4, 6, 1), -- Yunida, XI RPL 1, Matematika, Jam 6

-- Hari Selasa (2)
('22222222-2222-2222-2222-222222222222', 2, 1, 2, 1, 2), -- Fauzan, X RPL 1, Basis Data, Jam 1
('22222222-2222-2222-2222-222222222222', 2, 1, 2, 2, 2), -- Fauzan, X RPL 1, Basis Data, Jam 2
('11111111-1111-1111-1111-111111111111', 2, 2, 1, 3, 2), -- Bagus, X RPL 2, Pemrograman Web, Jam 3
('11111111-1111-1111-1111-111111111111', 2, 2, 1, 4, 2), -- Bagus, X RPL 2, Pemrograman Web, Jam 4
('33333333-3333-3333-3333-333333333333', 2, 4, 6, 5, 2), -- Yunida, XI RPL 2, Bahasa Inggris, Jam 5
('33333333-3333-3333-3333-333333333333', 2, 4, 6, 6, 2), -- Yunida, XI RPL 2, Bahasa Inggris, Jam 6

-- Hari Rabu (3)
('11111111-1111-1111-1111-111111111111', 2, 3, 3, 1, 3), -- Bagus, XI RPL 1, PBO, Jam 1
('11111111-1111-1111-1111-111111111111', 2, 3, 3, 2, 3), -- Bagus, XI RPL 1, PBO, Jam 2
('11111111-1111-1111-1111-111111111111', 2, 3, 3, 3, 3), -- Bagus, XI RPL 1, PBO, Jam 3
('33333333-3333-3333-3333-333333333333', 2, 1, 5, 4, 3), -- Yunida, X RPL 1, Bahasa Indo, Jam 4
('33333333-3333-3333-3333-333333333333', 2, 1, 5, 5, 3), -- Yunida, X RPL 1, Bahasa Indo, Jam 5
('22222222-2222-2222-2222-222222222222', 2, 5, 2, 7, 3), -- Fauzan, XII RPL 1, Basis Data, Jam 7
('22222222-2222-2222-2222-222222222222', 2, 5, 2, 8, 3), -- Fauzan, XII RPL 1, Basis Data, Jam 8

-- Hari Kamis (4)
('22222222-2222-2222-2222-222222222222', 2, 3, 2, 1, 4), -- Fauzan, XI RPL 1, Basis Data, Jam 1
('22222222-2222-2222-2222-222222222222', 2, 3, 2, 2, 4), -- Fauzan, XI RPL 1, Basis Data, Jam 2
('11111111-1111-1111-1111-111111111111', 2, 4, 3, 3, 4), -- Bagus, XI RPL 2, PBO, Jam 3
('11111111-1111-1111-1111-111111111111', 2, 4, 3, 4, 4), -- Bagus, XI RPL 2, PBO, Jam 4
('33333333-3333-3333-3333-333333333333', 2, 5, 4, 5, 4), -- Yunida, XII RPL 1, Matematika, Jam 5
('33333333-3333-3333-3333-333333333333', 2, 5, 4, 6, 4), -- Yunida, XII RPL 1, Matematika, Jam 6

-- Hari Jumat (5)
('33333333-3333-3333-3333-333333333333', 2, 2, 6, 1, 5), -- Yunida, X RPL 2, Bahasa Inggris, Jam 1
('33333333-3333-3333-3333-333333333333', 2, 2, 6, 2, 5), -- Yunida, X RPL 2, Bahasa Inggris, Jam 2
('22222222-2222-2222-2222-222222222222', 2, 4, 2, 3, 5), -- Fauzan, XI RPL 2, Basis Data, Jam 3
('22222222-2222-2222-2222-222222222222', 2, 4, 2, 4, 5), -- Fauzan, XI RPL 2, Basis Data, Jam 4
('11111111-1111-1111-1111-111111111111', 2, 5, 1, 5, 5); -- Bagus, XII RPL 1, Pemrograman Web, Jam 5


-- --------------------------------------------------------
-- 4. TRIGGERS UNTUK SUPABASE AUTH (SYNC EMAIL)
-- --------------------------------------------------------

-- Function to sync profile email from auth.users
CREATE OR REPLACE FUNCTION public.handle_sync_profile_email()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.profiles (id, email)
    VALUES (NEW.id, NEW.email);
    RETURN NEW;
  ELSIF (TG_OP = 'UPDATE') THEN
    UPDATE public.profiles
    SET email = NEW.email
    WHERE id = NEW.id;
    RETURN NEW;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger Sinkronisasi Profil
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE OF email ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_sync_profile_email();

-- --------------------------------------------------------
-- 5. TRIGGERS UNTUK JADWAL MENGAJAR
-- --------------------------------------------------------

-- Function to automatically calculate day_of_week from date
CREATE OR REPLACE FUNCTION public.set_hari_dari_tanggal()
RETURNS TRIGGER AS $$
BEGIN
   IF NEW.tanggal IS NOT NULL THEN
      NEW.hari := EXTRACT(ISODOW FROM NEW.tanggal);
   END IF;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger Sinkronisasi Jadwal
DROP TRIGGER IF EXISTS trg_jadwal_set_hari ON public.jadwal_mengajar;
CREATE TRIGGER trg_jadwal_set_hari
  BEFORE INSERT OR UPDATE ON public.jadwal_mengajar
  FOR EACH ROW
  EXECUTE FUNCTION public.set_hari_dari_tanggal();

-- --------------------------------------------------------
-- 6. TRIGGERS UNTUK JURNAL HARIAN (CEK IS_TELAT)
-- --------------------------------------------------------

-- Jika tanggal submit (CURRENT_DATE) dengan tanggal kelas (tanggal) > 3 hari, flag is_telat = true
CREATE OR REPLACE FUNCTION public.set_is_telat_jurnal()
RETURNS TRIGGER AS $$
BEGIN
   IF (CURRENT_DATE - NEW.tanggal) > 3 THEN
      NEW.is_telat := true;
   ELSE
      NEW.is_telat := false;
   END IF;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger Telat Jurnal
DROP TRIGGER IF EXISTS trg_jurnal_set_telat ON public.jurnal_harian;
CREATE TRIGGER trg_jurnal_set_telat
  BEFORE INSERT ON public.jurnal_harian
  FOR EACH ROW
  EXECUTE FUNCTION public.set_is_telat_jurnal();

-- ====================================================================================
-- END OF DUMP
-- ====================================================================================
